soft_skill_keywords = [
        'Dependability',
        'Empathetic',
        'Organizational Skills',
        'Interpersonal Skills',
        'Empathy',
        'Decision Making',
        'Cultural Awareness',
        'Presentation Skills',
        'Active Listening',
        'Analytical Thinking',
        'Innovation',
        'Multitasking',
        'Technical Skills',
        'Negotiation Skills',
        'Initiative',
        'Flexibility',
        'Emotional Intelligence',
        'Sales Skills',
        'Leadership',
        'Stakeholder Management',
        'Negotiation',
        'Positive Attitude',
        'Critical Thinking',
        'Collaboration',
        'Decision-Making',
        'Motivational',
        'Teamwork',
        'Analytical Skills',
        'Professionalism',
        'Communication',
        'Stress Management',
        'Motivation',
        'Listening Skills',
        'Interpersonal Communication',
        'Customer Service',
        'Problem Analysis',
        'Creativity',
        'Resilience',
        'Conflict Resolution',
        'Problem Solving',
        'Creative Thinking',
        'Prioritization',
        'Self-Motivation',
        'Goal Setting',
        'Conflict Management',
        'Networking',
        'Attention to Detail',
        'Influence',
        'Persuasion',
        'Resourcefulness',
        'Self-Discipline',
        'Problem-Solving',
        'Goal-Oriented',
        'Self-Confidence',
        'Time Management',
        'Planning',
        'Technical Proficiency',
        'Team Building',
        'Customer Focus',
        'Presentation',
        'Salesmanship',
        'Work Ethic',
        'Customer Relationship Management',
        'Cultural Sensitivity',
        'Diplomacy',
        'Punctuality',
        'Adaptability',
        'Resource Management',
        'Inclusive',
        'Project Management',
        'Growth Mindset',
        'Scheduling'
]


